# Generated by Django 4.2.1 on 2023-05-11 14:56

from django.db import migrations, models
import django.db.models.deletion
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_status_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(default=tasks.models.Status.get_default_value, on_delete=django.db.models.deletion.CASCADE, to='tasks.status'),
        ),
    ]
